stages:
  - test

test:
  stage: test
  script:
    - echo "Running tests"
    - python -V
    - pwd
    - ls
    - echo $PYTHONPATH
    - export PYTHONPATH=$PWD
    - python test
  only:
    - feature/classes
